% Building Ridge Filter
% First navigate to TOPAS extensions
RidgeFilterInitialize = {'# INITIALIZE';...
    '#Ts/G4DataDirectory = "/Applications/G4Data"';...
    '#Ts/UseQt = "true"';...
    'i:Ts/MaxInterruptedHistories = 100';...
    'i:Ts/NumberOfThreads = 6';...
    '                         ';...
    '# CHECKS';...
    'b:Ge/CheckForOverlaps = "True"';...
    'Ge/QuitIfOverlapDetected = "True"';...
    '                         ';...
    '# GEOMETRIES';...
    'd:Ge/World/HLX = 2.5 m';...
    'd:Ge/World/HLY = 2.5 m';...
    'd:Ge/World/HLZ = 2.5 m';...
    'Ge/World/Material  = "Air"';...
    'b:Ge/World/Invisible = "True"';...
    '                         ';...
    '# DEFINE GROUP ';...
    's:Ge/RidgeGroup/Parent = "World"';...
    's:Ge/RidgeGroup/Type   = "Group"';...
    'd:Ge/RidgeGroup/RotX   = 0.0 deg';...
    'd:Ge/RidgeGroup/RotY   = 0.0 deg';...
    'd:Ge/RidgeGroup/RotZ   = 0.0 deg';...
    'd:Ge/RidgeGroup/TransX = 0.0 cm';...
    'd:Ge/RidgeGroup/TransY = 0.0 cm';...
    'd:Ge/RidgeGroup/TransZ = 0.0 cm';...
    };

writecell(RidgeFilterInitialize,'RidgeFilter_4SpikeRows.txt')

% Build the Ridge Filter Groups
% construct various maps of (lateral) spike maps
p_spwidth = 0.80;
m_spwidth = 0.95;
d_spwidth = (12-2*p_spwidth-3*m_spwidth)/5;

p_spheight = 22.50;
m_spheight = 11.0;
d_spheight = 2.00;

%% RFG 1
o1 = 0;
xspikemap1_0 = [0, o1...
    o1+m_spwidth...
    o1+m_spwidth...
    o1+m_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth...
    ];
rem1 = 12 - xspikemap1_0(end);
xspikemap1_1 = [xspikemap1_0 xspikemap1_0(end)+rem1 xspikemap1_0(end)+rem1];

zspikemap1_1 = [0,...
    d_spheight+m_spheight...
    d_spheight+m_spheight...
    d_spheight...
    d_spheight...
    d_spheight+p_spheight...
    d_spheight+p_spheight...
    d_spheight...
    d_spheight...
    d_spheight+m_spheight...
    d_spheight+m_spheight...
    d_spheight...
    d_spheight...
    d_spheight+p_spheight...
    d_spheight+p_spheight...
    d_spheight...
    d_spheight...
    d_spheight+m_spheight...
    d_spheight+m_spheight...
    d_spheight...
    d_spheight...
    0];

figure(10)
clf
plot(xspikemap1_1,zspikemap1_1)

%% RFG 2
o1 = 12-(m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth)
xspikemap2_0 = [0, 0, o1, o1...
    o1+m_spwidth...
    o1+m_spwidth...
    o1+m_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth...
    o1+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth...
    ];
rem2 = 12 - xspikemap2_0(end);
xspikemap2_1 = [xspikemap2_0 xspikemap2_0(end)+rem2 xspikemap2_0(end)+rem2];

zspikemap2_1 = [0,...
    d_spheight,...
    d_spheight,...
    d_spheight+m_spheight...
    d_spheight+m_spheight...
    d_spheight...
    d_spheight...
    d_spheight+p_spheight...
    d_spheight+p_spheight...
    d_spheight...
    d_spheight...
    d_spheight+m_spheight...
    d_spheight+m_spheight...
    d_spheight...
    d_spheight...
    d_spheight+p_spheight...
    d_spheight+p_spheight...
    d_spheight...
    d_spheight...
    d_spheight+m_spheight...
    d_spheight+m_spheight...
    d_spheight...
    d_spheight...
    0];

%% RFG 3
o1 = 0.75;
xspikemap3_0 = [0, 0, o1, o1...
    o1+p_spwidth...
    o1+p_spwidth...
    o1+p_spwidth+d_spwidth...
    o1+p_spwidth+d_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth+d_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth+d_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth...
    o1+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth+d_spwidth+m_spwidth+d_spwidth+p_spwidth...
    ];
rem1 = 12 - xspikemap3_0(end);
xspikemap3_1 = [xspikemap3_0 xspikemap3_0(end)+rem1 xspikemap3_0(end)+rem1];

zspikemap3_1 = [0,...
    d_spheight,...
    d_spheight,...
    d_spheight+p_spheight...
    d_spheight+p_spheight...
    d_spheight...
    d_spheight...
    d_spheight+m_spheight...
    d_spheight+m_spheight...
    d_spheight...
    d_spheight...
    d_spheight+p_spheight...
    d_spheight+p_spheight...
    d_spheight...
    d_spheight...
    d_spheight+m_spheight...
    d_spheight+m_spheight...
    d_spheight...
    d_spheight...
    d_spheight+p_spheight...
    d_spheight+p_spheight...
    d_spheight...
    d_spheight...
    0];
%% 
figure(11)
clf
plot(xspikemap2_1,zspikemap2_1)
hold on
plot(xspikemap1_1,zspikemap1_1)
plot(xspikemap3_1,zspikemap3_1)

%% For y wedge spacings
spike_locations = [-30:1:30]; %mm
counter = 1;
for i = 3:3:length(spike_locations)
     RG1 = {'                       ';...
        strcat('############  RF ', string(counter), '#############');...
        strcat('s:Ge/RF', string(counter), '/Parent = "RidgeGroup"');...
        strcat('s:Ge/RF', string(counter), '/Type = "TsRidgeFilter"');...
        strcat('s:Ge/RF', string(counter), '/Material   = "Lucite"');...
        strcat('d:Ge/RF', string(counter), '/TransX = 0.0 mm');...
        strcat('d:Ge/RF', string(counter), '/TransY = ', string(spike_locations(i-2)), ' mm');...
        strcat('d:Ge/RF', string(counter), '/TransZ = ', string(max(zspikemap1_1)/2), ' mm');...
        strcat('s:Ge/RF', string(counter), '/DrawingStyle = "Solid"');...
        strcat('s:Ge/RF', string(counter), '/Color = "red"');...
        strcat('b:Ge/RF', string(counter), '/PrintInformation = "True"');...
        strcat('dv:Ge/RF', string(counter), '/XPoints =', string(length(xspikemap1_1)'));...
        strcat(num2str(xspikemap1_1), ' mm');...
        strcat('dv:Ge/RF', string(counter), '/ZPoints =', string(length(zspikemap1_1)'));...
        strcat(num2str(zspikemap1_1), ' mm');...
        strcat('d:Ge/RF', string(counter), '/Width = 12.0 mm');...
        strcat('d:Ge/RF', string(counter), '/Length = 1.0 mm');...
        strcat('dv:Ge/RF', string(counter), '/Displacement = 5 -24.0 -12.0 0.0 12.0 24.0 mm');...
        
        };
    
    counter = counter + 1;
    writecell(RG1,'RidgeFilter_4SpikeRows.txt','WriteMode','append')
    
    RG2 = {'                       ';...
        strcat('############  RF ', string(counter), '#############');...
        strcat('s:Ge/RF', string(counter), '/Parent = "RidgeGroup"');...
        strcat('s:Ge/RF', string(counter), '/Type = "TsRidgeFilter"');...
        strcat('s:Ge/RF', string(counter), '/Material   = "Lucite"');...
        strcat('d:Ge/RF', string(counter), '/TransX = 0.0 mm');...
        strcat('d:Ge/RF', string(counter), '/TransY = ', string(spike_locations(i-1)), ' mm');... %i-1
        strcat('d:Ge/RF', string(counter), '/TransZ = ', string(max(zspikemap2_1)/2), ' mm');...
        strcat('s:Ge/RF', string(counter), '/DrawingStyle = "Solid"');...
        strcat('s:Ge/RF', string(counter), '/Color = "red"');...
        strcat('b:Ge/RF', string(counter), '/PrintInformation = "True"');...
        strcat('dv:Ge/RF', string(counter), '/XPoints =', string(length(xspikemap2_1)));...
        strcat(num2str(xspikemap2_1), ' mm');...
        strcat('dv:Ge/RF', string(counter), '/ZPoints =', string(length(zspikemap2_1)));...
        strcat(num2str(zspikemap2_1), ' mm');...
        strcat('d:Ge/RF', string(counter), '/Width = 12.0 mm');...
        strcat('d:Ge/RF', string(counter), '/Length = 1.0 mm');...
        strcat('dv:Ge/RF', string(counter), '/Displacement = 5 -24.0 -12.0 0.0 12.0 24.0 mm');...
        
        };
    
    counter = counter + 1;
    writecell(RG2,'RidgeFilter_4SpikeRows.txt','WriteMode','append')
    
        
    RG3 = {'                       ';...
        strcat('############  RF', string(counter), '#############');...
        strcat('s:Ge/RF', string(counter), '/Parent = "RidgeGroup"');...
        strcat('s:Ge/RF', string(counter), '/Type = "TsRidgeFilter"');...
        strcat('s:Ge/RF', string(counter), '/Material   = "Lucite"');...
        strcat('d:Ge/RF', string(counter), '/TransX = 0.0 mm');...
        strcat('d:Ge/RF', string(counter), '/TransY = ', string(spike_locations(i)), ' mm');...
        strcat('d:Ge/RF', string(counter), '/TransZ = ', string(max(zspikemap3_1)/2), ' mm');...
        strcat('s:Ge/RF', string(counter), '/DrawingStyle = "Solid"');...
        strcat('s:Ge/RF', string(counter), '/Color = "red"');...
        strcat('b:Ge/RF', string(counter), '/PrintInformation = "True"');...
        strcat('dv:Ge/RF', string(counter), '/XPoints =', string(length(xspikemap3_1)));...
        strcat(num2str(xspikemap3_1), ' mm');...
        strcat('dv:Ge/RF', string(counter), '/ZPoints =', string(length(zspikemap3_1)));...
        strcat(num2str(zspikemap3_1), ' mm');...
        strcat('d:Ge/RF', string(counter), '/Width = 12.0 mm');...
        strcat('d:Ge/RF', string(counter), '/Length = 1.0 mm');...
        strcat('dv:Ge/RF', string(counter), '/Displacement = 5 -24.0 -12.0 0.0 12.0 24.0 mm');...
        
        };
    
    counter = counter + 1;
    writecell(RG3,'RidgeFilter_4SpikeRows.txt','WriteMode','append')
end


% Graphics
RidgeFilterBeamParameters = {
    '# GRAPHICS';...
    '#sv:Ph/Default/Modules = 1 "g4em-standard_opt0"';...
    '#b:Ts/PauseBeforeQuit = "True"';...
    '#s:Gr/ViewA/Type = "OpenGL"';...
    '#i:Gr/ViewA/WindowSizeX = 700';...
    '#i:Gr/ViewA/WindowSizeY = 700';...
    '#d:Gr/ViewA/Theta = 0 deg';...
    '#d:Gr/ViewA/Phi = 0 deg';...
    '#s:Gr/ViewA/Projection = "Orthogonal"';...
    '#d:Gr/ViewA/PerspectiveAngle = 0 deg';...
    '#u:Gr/ViewA/Zoom = 2';...
    '#b:Gr/ViewA/HiddenLineRemovalForTrajectories = "True"';...
    '#b:Gr/ViewA/IncludeAxes = "true"';...
    '#d:Gr/ViewA/AxesSize = 3 cm';...
    };
writecell(RidgeFilterBeamParameters,'RidgeFilter_4SpikeRows.txt','WriteMode','append')
% 
% Graphics
% RidgeFilterBeamParameters = {
%     '# GRAPHICS';...
%     'sv:Ph/Default/Modules = 1 "g4em-standard_opt0"';...
%     'b:Ts/PauseBeforeQuit = "True"';...
%     's:Gr/ViewA/Type = "OpenGL"';...
%     'i:Gr/ViewA/WindowSizeX = 700';...
%     'i:Gr/ViewA/WindowSizeY = 700';...
%     'd:Gr/ViewA/Theta = 0 deg';...
%     'd:Gr/ViewA/Phi = 0 deg';...
%     's:Gr/ViewA/Projection = "Orthogonal"';...
%     'd:Gr/ViewA/PerspectiveAngle = 0 deg';...
%     'u:Gr/ViewA/Zoom = 2';...
%     'b:Gr/ViewA/HiddenLineRemovalForTrajectories = "True"';...
%     'b:Gr/ViewA/IncludeAxes = "true"';...
%     'd:Gr/ViewA/AxesSize = 3 cm';...
%     };
% writecell(RidgeFilterBeamParameters,'RidgeFilter_4SpikeRows.txt','WriteMode','append')

    
    


